---
linters-settings:
  cyclop:
    max-complexity: 15
    package-average: 0.0
    skip-tests: true
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/ewohltman/discordgo-mock
  lll:
    line-length: 140
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - gci
    - goerr113
    - gofumpt
    - golint
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nonamedreturns
    - nosnakecase
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen
    - wrapcheck

run:
  timeout: 5m

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-dirs:
    - .github
    - build
    - web
  exclude-files:
    - zz_generated.*
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - cyclop
        - dupl
        - errcheck
        - errchkjson
        - forcetypeassert
        - gocyclo
        - gosec
        - nosnakecase
