---
name: pull_request
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'
          check-latest: true

      - name: Download dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57

      - name: Run tests
        run: make test

      - name: Run test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PATH="${PATH}:$(go env GOPATH)/bin"
          go install github.com/mattn/goveralls@latest
          goveralls -coverprofile=coverage.out -service=github

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
